spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 231869

  jpa:
    hibernate:
      ddl-auto: update   # create or update schema automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true